trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'

- script: |
    npm install
    npm run build
  displayName: 'Install dependencies and build'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '<YOUR-AZURE-SUBSCRIPTION>'
    appType: 'webAppLinux'
    appName: '<YOUR-APP-SERVICE-NAME>'
    package: '$(System.DefaultWorkingDirectory)'
