version: '3.8'
services:
  backend:
    build:
      context: ./internship-api
    container_name: internship-api
    ports:
      - "3000:3000"
    env_file:
      - ./internship-api/.env
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
