# azure-portal-guide.ps1 - Simple guide to access monitoring in Azure Portal

Write-Output "AZURE PORTAL MONITORING ACCESS GUIDE"
Write-Output "=============================================="
Write-Output ""

Write-Output "STEP-BY-STEP INSTRUCTIONS:"
Write-Output ""

# Step 1: Portal Access
Write-Output "STEP 1: Access Azure Portal"
Write-Output "--------------------------------------"
Write-Output "1. Open web browser"
Write-Output "2. Go to: https://portal.azure.com"
Write-Output "3. Sign in with your Azure account"
Write-Output ""

# Step 2: Resource Group
Write-Output "STEP 2: Navigate to Resource Group"
Write-Output "--------------------------------------"
Write-Output "1. In Azure Portal search bar, type: placement-tracker-rg"
Write-Output "2. Click on 'placement-tracker-rg' resource group"
Write-Output "3. You'll see all your project resources"
Write-Output ""

# Step 3: Container App Monitoring
Write-Output "STEP 3: Container App Health & Monitoring"
Write-Output "--------------------------------------"
Write-Output "Container App Health:"
Write-Output "1. Click 'internship-api' (Container App)"
Write-Output "2. Check Overview page for:"
Write-Output "   - Application Status (Running/Healthy)"
Write-Output "   - Application URL"
Write-Output "   - Quick metrics"
Write-Output ""
Write-Output "Container App Monitoring:"
Write-Output "1. In left menu under 'Monitoring':"
Write-Output "   - 'Metrics' - CPU, Memory, Requests"
Write-Output "   - 'Logs' - Application logs"
Write-Output "   - 'Log stream' - Live logs"
Write-Output "   - 'Diagnose and solve problems'"
Write-Output ""

# Step 4: Application Insights
Write-Output "STEP 4: Application Insights Monitoring"
Write-Output "--------------------------------------"
Write-Output "1. In resource group, find Application Insights resource"
Write-Output "2. Click on it and explore:"
Write-Output "   - 'Overview' - Health dashboard"
Write-Output "   - 'Performance' - Response times"
Write-Output "   - 'Failures' - Error rates"
Write-Output "   - 'Users' - User sessions"
Write-Output "   - 'Metrics' - Custom metrics"
Write-Output "   - 'Logs' - Advanced analytics"
Write-Output ""

Write-Output "YOUR PROJECT INFORMATION:"
Write-Output "--------------------------------------"
Write-Output "Resource Group: placement-tracker-rg"
Write-Output "Container App: internship-api"
Write-Output "Region: Central India"
Write-Output "App URL: https://internship-api.gentleforest-68343e46.centralindia.azurecontainerapps.io"
Write-Output ""

Write-Output "DIRECT PORTAL LINKS:"
Write-Output "--------------------------------------"
Write-Output "Main Portal: https://portal.azure.com"
Write-Output "Resource Groups: https://portal.azure.com/#view/HubsExtension/BrowseResourceGroups"
Write-Output "Container Apps: https://portal.azure.com/#view/HubsExtension/BrowseResource/resourceType/Microsoft.App%2FcontainerApps"
Write-Output ""

Write-Output "QUICK HEALTH CHECK:"
Write-Output "--------------------------------------"
Write-Output "1. Test your app: https://internship-api.gentleforest-68343e46.centralindia.azurecontainerapps.io"
Write-Output "2. Health endpoint: https://internship-api.gentleforest-68343e46.centralindia.azurecontainerapps.io/health"
Write-Output "3. Refresh a few times to generate data"
Write-Output "4. Check Azure Portal after 2-3 minutes"
Write-Output ""

Write-Output "TROUBLESHOOTING:"
Write-Output "--------------------------------------"
Write-Output "If you don't see resources:"
Write-Output "- Check you're in correct subscription"
Write-Output "- Verify region filter (Central India)"
Write-Output "- Refresh the portal page"
Write-Output ""
Write-Output "If no monitoring data:"
Write-Output "- Wait 5-10 minutes for data"
Write-Output "- Generate traffic first"
Write-Output "- Check Application Insights connection"
Write-Output ""

Write-Output "GUIDE COMPLETE!"
Write-Output "TIP: Bookmark your resource group for quick access"