#!/usr/bin/env pwsh
# azure-portal-monitoring-guide.ps1 - Step-by-step guide to view monitoring in Azure Portal

Write-Output "🌐 AZURE PORTAL MONITORING ACCESS GUIDE"
Write-Output "═══════════════════════════════════════════════════"
Write-Output ""

Write-Output "📋 STEP-BY-STEP INSTRUCTIONS:"
Write-Output ""

# Step 1: Portal Access
Write-Output "STEP 1: 🔑 Access Azure Portal"
Write-Output "───────────────────────────────────────────────────"
Write-Output "1. Open your web browser"
Write-Output "2. Go to: https://portal.azure.com"
Write-Output "3. Sign in with your Azure account credentials"
Write-Output ""

# Step 2: Resource Group
Write-Output "STEP 2: 📁 Navigate to Resource Group"
Write-Output "───────────────────────────────────────────────────"
Write-Output "1. In the Azure Portal search bar (top), type: placement-tracker-rg"
Write-Output "2. Click on 'placement-tracker-rg' resource group from results"
Write-Output "3. You'll see all your project resources listed"
Write-Output ""

# Step 3: Container App Monitoring
Write-Output "STEP 3: 🐳 Container App Health & Monitoring"
Write-Output "───────────────────────────────────────────────────"
Write-Output "Option A - Container App Direct:"
Write-Output "1. In resource group, click on 'internship-api' (Container App)"
Write-Output "2. In the left menu, under 'Monitoring', click:"
Write-Output "   • 📊 'Metrics' - CPU, Memory, Request metrics"
Write-Output "   • 📜 'Logs' - Application logs and diagnostics"
Write-Output "   • 🔍 'Log stream' - Live log streaming"
Write-Output "   • 💔 'Diagnose and solve problems' - Health insights"
Write-Output ""
Write-Output "Option B - Container App Overview:"
Write-Output "1. Click 'internship-api' container app"
Write-Output "2. On Overview page, you'll see:"
Write-Output "   • ✅ Application Status (Running/Healthy)"
Write-Output "   • 🌐 Application URL"
Write-Output "   • 📈 Quick metrics charts"
Write-Output "   • 🔄 Recent deployments"
Write-Output ""

# Step 4: Application Insights
Write-Output "STEP 4: 📊 Application Insights Monitoring"
Write-Output "───────────────────────────────────────────────────"
Write-Output "1. In resource group, look for Application Insights resource"
Write-Output "   (may be named like 'internship-api-insights' or similar)"
Write-Output "2. Click on the Application Insights resource"
Write-Output "3. In the left menu, explore:"
Write-Output "   • 📈 'Overview' - Quick health dashboard"
Write-Output "   • 🚀 'Performance' - Response times, dependencies"
Write-Output "   • 🔴 'Failures' - Error rates and exceptions"
Write-Output "   • 👥 'Users' - User sessions and behavior"
Write-Output "   • 📊 'Metrics' - Custom metrics and KPIs"
Write-Output "   • 🔍 'Logs' - Advanced log analytics (Kusto queries)"
Write-Output ""

# Step 5: Quick Health Checks
Write-Output "STEP 5: ⚡ Quick Health Checks"
Write-Output "───────────────────────────────────────────────────"
Write-Output "Container App Health:"
Write-Output "1. Go to Container App → Overview"
Write-Output "2. Check 'Provisioning State': Should be 'Succeeded'"
Write-Output "3. Check 'Running Status': Should be 'Running'"
Write-Output "4. Click 'Application URL' to test if app responds"
Write-Output ""
Write-Output "Application Insights Health:"
Write-Output "1. Go to Application Insights → Overview"
Write-Output "2. Look at 'Failed requests' chart (should be low/zero)"
Write-Output "3. Check 'Server response time' (should be reasonable)"
Write-Output "4. Verify 'Server requests' shows traffic"
Write-Output ""

Write-Output "═══════════════════════════════════════════════════"
Write-Output ""

# Current Resource Information
Write-Output "📍 YOUR PROJECT RESOURCES:"
Write-Output "───────────────────────────────────────────────────"
Write-Output "Resource Group: placement-tracker-rg"
Write-Output "Container App: internship-api"
Write-Output "Region: Central India"
Write-Output "Application URL: https://internship-api.gentleforest-68343e46.centralindia.azurecontainerapps.io"
Write-Output ""

# Direct Links
Write-Output "🔗 DIRECT PORTAL LINKS:"
Write-Output "───────────────────────────────────────────────────"
Write-Output "Resource Group:"
Write-Output "https://portal.azure.com/#view/HubsExtension/BrowseResourceGroups"
Write-Output ""
Write-Output "Container Apps:"
Write-Output "https://portal.azure.com/#view/HubsExtension/BrowseResource/resourceType/Microsoft.App%2FcontainerApps"
Write-Output ""
Write-Output "Application Insights:"
Write-Output "https://portal.azure.com/#view/HubsExtension/BrowseResource/resourceType/Microsoft.Insights%2Fcomponents"
Write-Output ""

Write-Output "═══════════════════════════════════════════════════"
Write-Output ""

# Troubleshooting
Write-Output "🔧 TROUBLESHOOTING TIPS:"
Write-Output "───────────────────────────────────────────────────"
Write-Output "If you don't see expected resources:"
Write-Output "1. ✅ Verify you're in the correct subscription"
Write-Output "2. ✅ Check the region filter (Central India)"
Write-Output "3. ✅ Ensure you have proper permissions"
Write-Output "4. ✅ Try refreshing the portal page"
Write-Output ""
Write-Output "If monitoring data is missing:"
Write-Output "1. ✅ Wait 5-10 minutes for data to appear"
Write-Output "2. ✅ Generate traffic to your app first"
Write-Output "3. ✅ Check Application Insights connection"
Write-Output ""

Write-Output "🎯 QUICK TEST:"
Write-Output "───────────────────────────────────────────────────"
Write-Output "To generate monitoring data right now:"
Write-Output "1. Open: https://internship-api.gentleforest-68343e46.centralindia.azurecontainerapps.io"
Write-Output "2. Refresh the page a few times"
Write-Output "3. Try: https://internship-api.gentleforest-68343e46.centralindia.azurecontainerapps.io/health"
Write-Output "4. Wait 2-3 minutes, then check Azure Portal metrics"
Write-Output ""

Write-Output "AZURE PORTAL MONITORING GUIDE COMPLETE!"
Write-Output ""
Write-Output "TIP: Bookmark the resource group page for quick access!"