# azure-free-tier-optimization.ps1 - Maximize Azure free tier usage

Write-Output "AZURE FREE TIER OPTIMIZATION STRATEGY"
Write-Output "======================================="
Write-Output ""

Write-Output "CURRENT FREE TIER STATUS:"
Write-Output "--------------------------------------"
Write-Output "✅ App Service Plan: FREE (F1 tier) - USD 0.00"
Write-Output "✅ Application Insights: FREE (5GB/month) - USD 0.00"
Write-Output "✅ SQL Database: FREE (serverless + free limit) - USD 0.00"
Write-Output "✅ Static Web App: FREE tier - USD 0.00"
Write-Output "✅ Cognitive Services: FREE tier - USD 0.00"
Write-Output "✅ Log Analytics: FREE (5GB/month) - USD 0.00"
Write-Output ""
Write-Output "SERVICES THAT COST MONEY:"
Write-Output "--------------------------------------"
Write-Output "💰 Container App: ~USD 0.50-1.00/day (consumption pricing)"
Write-Output "💰 Container Registry: ~USD 0.17/day (Basic tier)"
Write-Output "💰 Storage Account: ~USD 0.01-0.05/day (minimal)"
Write-Output ""

Write-Output "STRATEGY TO MAKE EVERYTHING FREE:"
Write-Output "======================================="
Write-Output ""

Write-Output "OPTION 1: PAUSE CONTAINER APP (RECOMMENDED)"
Write-Output "--------------------------------------"
Write-Output "✅ Keeps monitoring infrastructure"
Write-Output "✅ Can resume anytime"
Write-Output "✅ Saves USD 0.50-1.00/day"
Write-Output ""
Write-Output "Commands:"
Write-Output "# Scale to zero (app sleeps but stays configured)"
Write-Output "az containerapp update --name internship-api --resource-group placement-tracker-rg --min-replicas 0 --max-replicas 1"
Write-Output ""
Write-Output "# Resume when needed"
Write-Output "az containerapp update --name internship-api --resource-group placement-tracker-rg --min-replicas 1 --max-replicas 3"
Write-Output ""

Write-Output "OPTION 2: USE AZURE FREE CREDITS"
Write-Output "--------------------------------------"
Write-Output "✅ New Azure accounts get USD 200 free credits"
Write-Output "✅ These credits cover all usage for months"
Write-Output "✅ Check your credit balance"
Write-Output ""
Write-Output "Commands to check credits:"
Write-Output "az account show --query '{subscriptionId:id,name:name}'"
Write-Output ""

Write-Output "OPTION 3: OPTIMIZE CONTAINER REGISTRY"
Write-Output "--------------------------------------"
Write-Output "✅ Switch to Basic tier storage optimization"
Write-Output "✅ Or delete unused images"
Write-Output ""
Write-Output "Commands:"
Write-Output "# Check repository size"
Write-Output "az acr repository list --name cloudprojectacr"
Write-Output ""
Write-Output "# Clean up old images (if any)"
Write-Output "az acr repository delete --name cloudprojectacr --repository internship-api --tag old-tag --yes"
Write-Output ""

Write-Output "OPTION 4: ALTERNATIVE FREE HOSTING"
Write-Output "--------------------------------------"
Write-Output "✅ Move app to Azure Static Web Apps (100% free)"
Write-Output "✅ Or use Azure App Service Free tier"
Write-Output "✅ Keep monitoring with free Application Insights"
Write-Output ""

Write-Output "======================================="
Write-Output ""

Write-Output "MY RECOMMENDATION FOR TOMORROW:"
Write-Output "--------------------------------------"
Write-Output ""
Write-Output "STEP 1: Check your Azure free credits first"
Write-Output "STEP 2: If no credits, scale Container App to zero"
Write-Output "STEP 3: Keep all monitoring infrastructure (it's free)"
Write-Output "STEP 4: Resume Container App when demonstrating"
Write-Output ""

Write-Output "DEMONSTRATION STRATEGY:"
Write-Output "--------------------------------------"
Write-Output "Morning: Scale Container App to 0 replicas (free)"
Write-Output "Demo time: Scale up to 1 replica (minimal cost for demo duration)"
Write-Output "After demo: Scale back to 0 replicas (free again)"
Write-Output ""
Write-Output "This gives you:"
Write-Output "✅ FREE monitoring dashboard all day"
Write-Output "✅ Working demo when needed"
Write-Output "✅ Cost only during actual demo (~USD 0.10-0.20)"
Write-Output ""

Write-Output "AZURE FREE ACCOUNT LIMITS:"
Write-Output "--------------------------------------"
Write-Output "✅ 750 hours App Service (F1) - FREE"
Write-Output "✅ 5GB Application Insights - FREE"
Write-Output "✅ 5GB Log Analytics - FREE"
Write-Output "✅ 32GB Azure SQL Database - FREE"
Write-Output "✅ 5GB Storage (LRS) - FREE"
Write-Output "✅ 240 vCPU hours Container Instances - FREE"
Write-Output ""
Write-Output "Your project uses VERY little of these limits!"
Write-Output ""

Write-Output "COST MONITORING:"
Write-Output "--------------------------------------"
Write-Output "Set up free tier monitoring:"
Write-Output "az consumption budget create --budget-name free-tier-budget --amount 1 --time-grain Monthly --resource-group placement-tracker-rg"