# check-credits-alternative.ps1 - Alternative ways to check Azure credits

Write-Output "ALTERNATIVE WAYS TO CHECK AZURE FOR STUDENTS CREDITS"
Write-Output "===================================================="
Write-Output ""

Write-Output "LINK UNREACHABLE - TRY THESE ALTERNATIVES:"
Write-Output "--------------------------------------"
Write-Output ""

Write-Output "METHOD 1: Azure Portal Cost Management (RELIABLE)"
Write-Output "--------------------------------------"
Write-Output "1. Go to: https://portal.azure.com"
Write-Output "2. In the search bar, type: Cost Management"
Write-Output "3. Click 'Cost Management + Billing'"
Write-Output "4. On the left menu, click 'Cost analysis'"
Write-Output "5. Make sure 'Azure for Students' subscription is selected"
Write-Output "6. Look at the total spend for current month"
Write-Output ""

Write-Output "METHOD 2: Azure Portal Subscriptions Page"
Write-Output "--------------------------------------"
Write-Output "1. Go to: https://portal.azure.com"
Write-Output "2. Search for: Subscriptions"
Write-Output "3. Click on 'Azure for Students'"
Write-Output "4. Look for 'Credits and billing' or 'Cost management'"
Write-Output "5. Check current usage and remaining credits"
Write-Output ""

Write-Output "METHOD 3: Azure Education Hub"
Write-Output "--------------------------------------"
Write-Output "1. Try: https://aka.ms/azurestudents"
Write-Output "2. Sign in with your account"
Write-Output "3. Look for credit balance information"
Write-Output "4. May redirect to proper portal"
Write-Output ""

Write-Output "METHOD 4: Check Your Current Usage Patterns"
Write-Output "--------------------------------------"
Write-Output "Based on your CLI results, your costs show 'None':"
Write-Output "- Container Registry: Free usage"
Write-Output "- App Service: Free F1 tier"
Write-Output "- SQL Database: Free serverless tier"
Write-Output ""
Write-Output "This suggests you're either:"
Write-Output "a) Using free credits successfully"
Write-Output "b) Staying within free tier limits"
Write-Output ""

Write-Output "METHOD 5: Azure CLI Cost Analysis"
Write-Output "--------------------------------------"