# check-azure-credits.ps1 - Check Azure for Students credits and usage

Write-Output "AZURE FOR STUDENTS CREDIT CHECK"
Write-Output "================================="
Write-Output ""

Write-Output "YOUR SUBSCRIPTION DETAILS:"
Write-Output "--------------------------------------"
Write-Output "Subscription: Azure for Students"
Write-Output "ID: 9dccc1a5-37e0-4f73-aa2c-64864cdbbedb"
Write-Output "Status: Enabled"
Write-Output ""

Write-Output "METHODS TO CHECK YOUR CREDIT BALANCE:"
Write-Output "======================================"
Write-Output ""

Write-Output "METHOD 1: Azure Sponsorship Portal (RECOMMENDED)"
Write-Output "--------------------------------------"
Write-Output "Direct link: https://www.microsoftazuresponsorship.com/Balance"
Write-Output ""
Write-Output "What you'll see:"
Write-Output "- Remaining credit balance (out of USD 100)"
Write-Output "- Credit expiration date"
Write-Output "- Usage breakdown by service"
Write-Output ""

Write-Output "METHOD 2: Azure Portal Cost Management"
Write-Output "--------------------------------------"
Write-Output "1. Go to: https://portal.azure.com"
Write-Output "2. Search for 'Cost Management + Billing'"
Write-Output "3. Click on 'Cost analysis'"
Write-Output "4. Select your subscription: Azure for Students"
Write-Output "5. View current month spending"
Write-Output ""

Write-Output "METHOD 3: Azure CLI Cost Commands"
Write-Output "--------------------------------------"
Write-Output "Try these commands:"
Write-Output ""

Write-Output "# Check subscription details"
Write-Output "az account show --output table"
Write-Output ""

Write-Output "# Check current usage (if available)"
Write-Output "az consumption usage list --top 5 --output table"
Write-Output ""

Write-Output "METHOD 4: Azure Mobile App"
Write-Output "--------------------------------------"
Write-Output "Download Azure mobile app and check cost management section"
Write-Output ""

Write-Output "======================================"
Write-Output ""

Write-Output "WHAT TO LOOK FOR:"
Write-Output "--------------------------------------"
Write-Output "Credit Status:"
Write-Output "- Starting amount: USD 100"
Write-Output "- Current remaining: ?? (check portal)"
Write-Output "- Expiration: 12 months from activation"
Write-Output ""
Write-Output "Usage Estimate for Your Project:"
Write-Output "- Daily cost: ~USD 0.70-1.50"
Write-Output "- Monthly projection: ~USD 21-45"
Write-Output "- Credits should last: 2-4+ months"
Write-Output ""

Write-Output "DECISION MATRIX:"
Write-Output "--------------------------------------"
Write-Output "IF you have USD 20+ credits remaining:"
Write-Output "  -> Keep everything running worry-free"
Write-Output "  -> Your project costs are very low"
Write-Output ""
Write-Output "IF you have USD 5-20 credits remaining:"
Write-Output "  -> Run normally but monitor daily"
Write-Output "  -> Consider scaling optimizations"
Write-Output ""
Write-Output "IF you have less than USD 5 credits:"
Write-Output "  -> Scale Container App to zero"
Write-Output "  -> Use free tiers only"
Write-Output ""

Write-Output "IMMEDIATE NEXT STEPS:"
Write-Output "======================================="
Write-Output "1. Open: https://www.microsoftazuresponsorship.com/Balance"
Write-Output "2. Check your remaining credit balance"
Write-Output "3. Based on balance, decide your strategy:"
Write-Output ""
Write-Output "   High credits (USD 20+): Keep running"
Write-Output "   Medium credits (USD 5-20): Monitor usage"
Write-Output "   Low credits (Under USD 5): Scale to zero"
Write-Output ""
Write-Output "4. Come back and tell me your balance!"
Write-Output "   I'll give you the perfect optimization strategy"