# cost-analysis.ps1 - Azure cost analysis for cloud-project

Write-Output "AZURE COST ANALYSIS - CLOUD PROJECT"
Write-Output "==========================================="
Write-Output ""

Write-Output "CURRENT RESOURCES & COST IMPLICATIONS:"
Write-Output "--------------------------------------"
Write-Output ""

Write-Output "1. CONTAINER APP (internship-api)"
Write-Output "   Type: Microsoft.App/containerApps"
Write-Output "   CPU: 0.5 cores"
Write-Output "   Memory: 1 GiB"
Write-Output "   Status: Running"
Write-Output "   Cost Impact: LOW - Container Apps have consumption pricing"
Write-Output "   Estimated: ~USD 0.50-2.00 per day (based on usage)"
Write-Output ""

Write-Output "2. CONTAINER REGISTRY (cloudprojectacr)"
Write-Output "   Type: Microsoft.ContainerRegistry/registries"
Write-Output "   Cost Impact: LOW - Basic tier storage"
Write-Output "   Estimated: ~USD 0.17 per day (Basic tier)"
Write-Output ""

Write-Output "3. APPLICATION INSIGHTS (internship-api-ai)"
Write-Output "   Type: microsoft.insights/components"
Write-Output "   Cost Impact: MINIMAL - First 5GB free per month"
Write-Output "   Estimated: USD 0.00 (within free tier)"
Write-Output ""

Write-Output "4. LOG ANALYTICS WORKSPACE"
Write-Output "   Type: Microsoft.OperationalInsights/workspaces"
Write-Output "   Cost Impact: MINIMAL - First 5GB free per month"
Write-Output "   Estimated: USD 0.00 (within free tier)"
Write-Output ""

Write-Output "5. APP SERVICE PLAN (ASP-placementtrackerrg-985b)"
Write-Output "   Type: Microsoft.Web/serverFarms"
Write-Output "   Cost Impact: MEDIUM-HIGH (if not Free tier)"
Write-Output "   Estimated: USD 0.00-15.00+ per day (depends on tier)"
Write-Output ""

Write-Output "6. SQL DATABASE (PlacementTrackerDB)"
Write-Output "   Type: Microsoft.Sql/servers/databases"
Write-Output "   Kind: serverless,freelimit"
Write-Output "   Cost Impact: MINIMAL (serverless + free limit)"
Write-Output "   Estimated: USD 0.00-0.50 per day"
Write-Output ""

Write-Output "7. STORAGE ACCOUNT (placementtrackerstorage)"
Write-Output "   Type: Microsoft.Storage/storageAccounts"
Write-Output "   Cost Impact: MINIMAL"
Write-Output "   Estimated: USD 0.01-0.10 per day"
Write-Output ""

Write-Output "8. COGNITIVE SERVICES (placement-ai-service)"
Write-Output "   Type: Microsoft.CognitiveServices/accounts"
Write-Output "   Cost Impact: MINIMAL (likely Free tier)"
Write-Output "   Estimated: USD 0.00-0.50 per day"
Write-Output ""

Write-Output "9. STATIC WEB APP (myfrontendapp)"
Write-Output "   Type: Microsoft.Web/staticSites"
Write-Output "   Cost Impact: MINIMAL (Free tier available)"
Write-Output "   Estimated: USD 0.00 per day"
Write-Output ""

Write-Output "==========================================="
Write-Output ""

Write-Output "TOTAL ESTIMATED DAILY COST:"
Write-Output "--------------------------------------"
Write-Output "Conservative estimate: USD 1.00-3.00 per day"
Write-Output "Maximum estimate: USD 2.00-18.00 per day"
Write-Output ""
Write-Output "Until tomorrow morning (~12 hours): USD 0.50-9.00"
Write-Output ""

Write-Output "COST OPTIMIZATION RECOMMENDATIONS:"
Write-Output "--------------------------------------"
Write-Output "1. IMMEDIATE (to minimize costs tonight):"
Write-Output "   - Container App: Already optimized (0.5 CPU, 1GB RAM)"
Write-Output "   - Most services: Already using free/minimal tiers"
Write-Output ""
Write-Output "2. IF YOU WANT ZERO COST:"
Write-Output "   - Stop Container App (but this breaks monitoring demo)"
Write-Output "   - Scale down App Service Plan to Free tier"
Write-Output ""
Write-Output "3. MONITORING WITHOUT HIGH COST:"
Write-Output "   - Keep Container App running (minimal cost)"
Write-Output "   - Application Insights stays in free tier"
Write-Output "   - Log Analytics stays in free tier"
Write-Output ""

Write-Output "COST MONITORING COMMANDS:"
Write-Output "--------------------------------------"
Write-Output "Check current usage:"
Write-Output "   az consumption usage list --top 10"
Write-Output ""
Write-Output "Check billing:"
Write-Output "   az billing account list"
Write-Output ""
Write-Output "Set up budget alerts:"
Write-Output "   az consumption budget create --budget-name daily-budget --amount 5 --time-grain Daily"
Write-Output ""

Write-Output "RECOMMENDATION FOR TONIGHT:"
Write-Output "--------------------------------------"
Write-Output "KEEP RUNNING - Your current setup should cost less than USD 1-2"
Write-Output "until tomorrow morning. This preserves your monitoring demo"
Write-Output "while keeping costs minimal."
Write-Output ""
Write-Output "Most services are in free tiers or very low-cost consumption pricing."