# cost-control.ps1 - Cost control options

Write-Output "COST CONTROL OPTIONS FOR TONIGHT"
Write-Output "=================================="
Write-Output ""

Write-Output "GOOD NEWS: App Service Plan is FREE TIER (F1)!"
Write-Output "This means your major cost drivers are minimal."
Write-Output ""

Write-Output "CURRENT COST SITUATION:"
Write-Output "--------------------------------------"
Write-Output "App Service Plan: USD 0.00 (Free tier F1)"
Write-Output "Container App: ~USD 0.50-1.00 (consumption pricing)"
Write-Output "Container Registry: ~USD 0.17 (Basic tier)"
Write-Output "Application Insights: USD 0.00 (free tier)"
Write-Output "SQL Database: USD 0.00 (serverless + free limit)"
Write-Output "Storage: ~USD 0.01-0.05 (minimal usage)"
Write-Output "Static Web App: USD 0.00 (free tier)"
Write-Output "Cognitive Services: USD 0.00 (likely free tier)"
Write-Output ""
Write-Output "TOTAL ESTIMATED COST UNTIL TOMORROW: USD 0.70-1.50"
Write-Output ""

Write-Output "COST CONTROL OPTIONS:"
Write-Output "--------------------------------------"
Write-Output ""
Write-Output "OPTION 1: KEEP EVERYTHING RUNNING (RECOMMENDED)"
Write-Output "Cost: ~USD 0.70-1.50 until tomorrow"
Write-Output "Benefits: Full monitoring demo works, minimal cost"
Write-Output "Command: # No action needed"
Write-Output ""

Write-Output "OPTION 2: STOP CONTAINER APP (SAVE ~USD 0.50)"
Write-Output "Cost: ~USD 0.20-1.00 until tomorrow"
Write-Output "Impact: Breaks monitoring demo, but saves on compute"
Write-Output "Command: az containerapp revision deactivate --name internship-api --resource-group placement-tracker-rg --revision-name internship-api--0000020"
Write-Output ""

Write-Output "OPTION 3: SCALE CONTAINER APP TO ZERO"
Write-Output "Cost: ~USD 0.17-0.50 until tomorrow"
Write-Output "Impact: App sleeps but can wake up on demand"
Write-Output "Command: az containerapp update --name internship-api --resource-group placement-tracker-rg --min-replicas 0 --max-replicas 1"
Write-Output ""

Write-Output "RESTART COMMANDS (if you stop anything):"
Write-Output "--------------------------------------"
Write-Output "Restart Container App:"
Write-Output "az containerapp revision activate --name internship-api --resource-group placement-tracker-rg --revision-name internship-api--0000020"
Write-Output ""
Write-Output "Reset scaling:"
Write-Output "az containerapp update --name internship-api --resource-group placement-tracker-rg --min-replicas 1 --max-replicas 10"
Write-Output ""

Write-Output "MY RECOMMENDATION:"
Write-Output "=================================="
Write-Output "KEEP EVERYTHING RUNNING"
Write-Output ""
Write-Output "Reasons:"
Write-Output "1. Total cost is very low (~USD 1.50 max until tomorrow)"
Write-Output "2. Your monitoring demo works perfectly"
Write-Output "3. Most services are in free tiers already"
Write-Output "4. Container App is minimal spec (0.5 CPU, 1GB RAM)"
Write-Output ""
Write-Output "The cost is negligible for maintaining a working demo!"

Write-Output ""
Write-Output "COST MONITORING:"
Write-Output "--------------------------------------"
Write-Output "To check actual usage tomorrow:"
Write-Output "az billing account list"
Write-Output "az consumption usage list --start-date 2025-10-28 --end-date 2025-10-29"