# Frontend-Backend Integration Demonstration Guide
# This script helps demonstrate how your frontend connects to the backend API

Write-Output "======================================================="
Write-Output "🎯 FRONTEND-BACKEND INTEGRATION DEMONSTRATION"
Write-Output "======================================================="
Write-Output ""

$baseUrl = "https://internship-api.gentleforest-68343e46.centralindia.azurecontainerapps.io"

Write-Output "📋 DEMONSTRATION OVERVIEW"
Write-Output "========================="
Write-Output ""
Write-Output "This demonstration shows how your frontend HTML pages"
Write-Output "communicate with your Node.js backend API through:"
Write-Output ""
Write-Output "✅ RESTful API calls"
Write-Output "✅ JSON data exchange"
Write-Output "✅ File uploads (resume handling)"
Write-Output "✅ Real-time data fetching"
Write-Output "✅ Error handling"
Write-Output ""

Write-Output "🌐 APPLICATION ARCHITECTURE"
Write-Output "============================="
Write-Output ""
Write-Output "Frontend (HTML/JS) ←→ Backend API (Node.js) ←→ SQL Database"
Write-Output ""
Write-Output "Frontend Files:"
Write-Output "• index.html      - Landing page"
Write-Output "• student.html    - Student management (ADD/VIEW students)"
Write-Output "• admin.html      - Admin interface"
Write-Output "• faculty.html    - Faculty interface"
Write-Output ""
Write-Output "Backend API Endpoints:"
Write-Output "• GET  /api/students     - Fetch all students"
Write-Output "• POST /api/students     - Add new student"
Write-Output "• GET  /api/internships  - Fetch internships"
Write-Output "• POST /api/internships  - Add internship"
Write-Output ""

Write-Output "🔄 STEP 1: Testing Backend API Directly"
Write-Output "========================================="
Write-Output ""
Write-Output "First, let's verify the backend API is working:"
Write-Output ""

try {
    Write-Output "Testing: GET $baseUrl/api/students"
    $studentsResponse = Invoke-WebRequest -Uri "$baseUrl/api/students" -UseBasicParsing -TimeoutSec 10
    Write-Output "✅ Status: HTTP $($studentsResponse.StatusCode)"
    Write-Output "✅ Response Length: $($studentsResponse.Content.Length) bytes"
    
    # Parse JSON to show data structure
    $studentsData = $studentsResponse.Content | ConvertFrom-Json
    $studentCount = if ($studentsData -is [array]) { $studentsData.Count } else { 1 }
    Write-Output "✅ Students Found: $studentCount records"
    Write-Output ""
    
    if ($studentCount -gt 0) {
        Write-Output "Sample Student Data Structure:"
        $sampleStudent = if ($studentsData -is [array]) { $studentsData[0] } else { $studentsData }
        Write-Output ($sampleStudent | ConvertTo-Json -Depth 2)
    }
} catch {
    Write-Output "❌ API Error: $($_.Exception.Message)"
}

Write-Output ""
Write-Output "🖥️  STEP 2: Frontend-Backend Integration Points"
Write-Output "================================================"
Write-Output ""

Write-Output "The frontend JavaScript makes these API calls:"
Write-Output ""
Write-Output "1. LOADING STUDENTS (student.html line ~28):"
Write-Output "   JavaScript Code:"
Write-Output "   ```javascript"
Write-Output "   async function loadStudents() {"
Write-Output "     const res = await fetch('/api/students');"
Write-Output "     const students = await res.json();"
Write-Output "     // Display students in HTML list"
Write-Output "   }"
Write-Output "   ```"
Write-Output ""

Write-Output "2. ADDING STUDENTS (student.html line ~40-80):"
Write-Output "   JavaScript Code:"
Write-Output "   ```javascript"
Write-Output "   const res = await fetch('/api/students', {"
Write-Output "     method: 'POST',"
Write-Output "     headers: { 'Content-Type': 'application/json' },"
Write-Output "     body: JSON.stringify(studentData)"
Write-Output "   });"
Write-Output "   ```"
Write-Output ""

Write-Output "🎬 STEP 3: Live Demonstration Instructions"
Write-Output "==========================================="
Write-Output ""
Write-Output "TO SHOW YOUR MENTOR:"
Write-Output ""
Write-Output "1. Open the live application URL:"
Write-Output "   $baseUrl"
Write-Output ""
Write-Output "2. Navigate to student.html by adding /student.html to URL:"
Write-Output "   $baseUrl/student.html"
Write-Output ""
Write-Output "3. Show the Student List Loading:"
Write-Output "   • Point out that the list appears automatically"
Write-Output "   • Explain: 'This data comes from our SQL database via API'"
Write-Output "   • Open browser Developer Tools (F12) → Network tab"
Write-Output "   • Refresh page to show the API call to /api/students"
Write-Output ""
Write-Output "4. Demonstrate Adding a New Student:"
Write-Output "   • Fill in the form (Roll Number, Name, Email)"
Write-Output "   • Upload a sample resume file"
Write-Output "   • Click 'Add Student'"
Write-Output "   • Show the API call in Network tab (POST /api/students)"
Write-Output "   • Point out the student appears in the list immediately"
Write-Output ""

Write-Output "🔍 STEP 4: Technical Deep Dive"
Write-Output "==============================="
Write-Output ""
Write-Output "EXPLAIN TO YOUR MENTOR:"
Write-Output ""
Write-Output "A. Data Flow:"
Write-Output "   Frontend Form → JavaScript → JSON → API → Database → JSON → Frontend"
Write-Output ""
Write-Output "B. Error Handling:"
Write-Output "   • Try-catch blocks in JavaScript"
Write-Output "   • HTTP status code checking"
Write-Output "   • User-friendly error messages"
Write-Output ""
Write-Output "C. File Upload Process:"
Write-Output "   • Frontend converts file to Base64"
Write-Output "   • Sends to API via JSON"
Write-Output "   • Backend stores in Azure Blob Storage"
Write-Output "   • Returns URL for frontend to display"
Write-Output ""

Write-Output "🛠️  STEP 5: Backend Code Walkthrough"
Write-Output "======================================"
Write-Output ""
Write-Output "Show your mentor the backend code:"
Write-Output ""
Write-Output "File: internship-api/index.js"
Write-Output ""
Write-Output "Key Integration Points:"
Write-Output "• Line ~1-20:   Dependencies (Express, CORS, SQL)"
Write-Output "• Line ~200+:   API Routes (/api/students, /api/internships)"
Write-Output "• Line ~300+:   Database connection and queries"
Write-Output "• Line ~500+:   File upload handling"
Write-Output ""

Write-Output "🎯 STEP 6: Browser Developer Tools Demo"
Write-Output "========================================"
Write-Output ""
Write-Output "SHOW YOUR MENTOR IN BROWSER (F12):"
Write-Output ""
Write-Output "1. Network Tab:"
Write-Output "   • See all API calls being made"
Write-Output "   • View request/response data"
Write-Output "   • Check HTTP status codes"
Write-Output ""
Write-Output "2. Console Tab:"
Write-Output "   • View JavaScript logs"
Write-Output "   • See any errors"
Write-Output "   • Check API responses"
Write-Output ""
Write-Output "3. Application Tab:"
Write-Output "   • LocalStorage/SessionStorage usage"
Write-Output "   • Cookies if authentication is used"
Write-Output ""

Write-Output "📊 STEP 7: Database Integration Proof"
Write-Output "====================================="
Write-Output ""
Write-Output "To prove data persistence:"
Write-Output ""
Write-Output "1. Add a student through the frontend"
Write-Output "2. Close the browser completely"
Write-Output "3. Reopen and navigate to student.html"
Write-Output "4. Show the student is still there"
Write-Output "5. Explain: 'Data is stored in Azure SQL Database'"
Write-Output ""

Write-Output "🎉 INTEGRATION DEMONSTRATION COMPLETE!"
Write-Output "======================================="
Write-Output ""
Write-Output "KEY POINTS TO EMPHASIZE:"
Write-Output ""
Write-Output "✅ Frontend and Backend are completely separated"
Write-Output "✅ Communication happens through RESTful APIs"
Write-Output "✅ Data persists in cloud database"
Write-Output "✅ Real-time updates without page refresh"
Write-Output "✅ Proper error handling throughout"
Write-Output "✅ File uploads work end-to-end"
Write-Output "✅ Responsive and user-friendly interface"
Write-Output ""
Write-Output "TECHNICAL STACK DEMONSTRATED:"
Write-Output "• Frontend: HTML5, CSS3, Vanilla JavaScript"
Write-Output "• Backend: Node.js, Express.js"
Write-Output "• Database: Azure SQL Database"
Write-Output "• Storage: Azure Blob Storage"
Write-Output "• Hosting: Azure Container Apps"
Write-Output ""
Write-Output "🚀 Your full-stack application is working perfectly!"