name: Node.js CI

# Run workflow on pushes to main branch and PRs
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      NODE_ENV: development

    steps:
    # Step 1: Checkout the code
    - uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Step 3: Install dependencies
    - run: npm install

    # Step 4: Run tests
    - run: npm test

    # Step 5: Build (if you have a build script)
    - run: npm run build
