name: "OWASP ZAP Security Scan"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  zap-scan:
    name: OWASP ZAP Baseline Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies and start local server
      run: |
        npm install -g http-server
        http-server frontend -p 8080 &
        sleep 10  # Wait for server to start
        
    - name: Run OWASP ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.12.0
      with:
        target: 'http://localhost:8080'
        rules_file_name: '.zap/rules.tsv'
        cmd_options: '-a -m 5'
        
    - name: Upload ZAP Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: zap-report
        path: report_html.html
        
    - name: Create ZAP rules file (if not exists)
      run: |
        mkdir -p .zap
        echo -e "10023\tIGNORE\tInformation Disclosure - Debug Error Messages" > .zap/rules.tsv